spring:
  application:
    name: UserService
  datasource:
    url: jdbc:postgresql://localhost:5432/userservice
    username: postgres
    password: root
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      dialect :  org.hibernate.dialect.PostgreSQLDialect
  cloud:
    openfeign:
      client:
        config:
          default :
            connectTimeout: 2000
            readTimeout: 3000


    config:
      enabled: false
#  security:
#    user:
#      name: admin
#      password: admin
#    import: optional:configserver:http://localhost:8086


logging:
  level:
    com.lcwd.user : DEBUG

server:
  port: 8081

eureka:
  instance:
    prefer-ip-address: true
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone : http://localhost:8761/eureka


external :
  service :
    url :
      hotel : "http://localhost:8082/hotel"
      ratingService : "http://localhost:8083/rating"




management:
  endpoints:
    web:
      exposure:
        include:
          - health
          - info
          - metrics
  endpoint:
    health:
      show-details: always

  health:
    circuitbreakers:
      enabled: true


resilience4j:

  timelimiter:
    instances:
      ratingTimeLimiter:
        timeoutDuration: 2s


  circuitbreaker:
    instances:
      ratingCircuitBreaker :
        registerHealthIndicator: true
        automaticTransitionFromOpenToHalfOpenEnabled: true
        eventConsumerBufferSize: 10
        failureRateThreshold: 50
        minimumNumberOfCalls: 5
        waitDurationInOpenState: 30s     # with this the downstream will recover in 30s meanwhile the circutit breaker will be in open state
        permittedNumberOfCallsInHalfOpenState: 3
        slidingWindowSize: 10
        slidingWindowType: COUNT_BASED

      hotelCircuitBreaker:
        registerHealthIndicator: true
        automaticTransitionFromOpenToHalfOpenEnabled: true
        eventConsumerBufferSize: 10
        failureRateThreshold: 50
        minimumNumberOfCalls: 5
        waitDurationInOpenState: 30s     # with this the downstream will recover in 30s meanwhile the circutit breaker will be in open state
        permittedNumberOfCallsInHalfOpenState: 3
        slidingWindowSize: 10
        slidingWindowType: COUNT_BASED

  retry:
    instances:
      ratingRetryInstance :
        maxAttempts: 3
        waitDuration: 200ms
        retryExceptions:
          - java.net.SocketTimeoutException
          - org.springframework.web.client.HttpServerErrorException
        ignoreExceptions:
          - java.lang.IllegalArgumentException

      hotelRetryInstance:
        maxAttempts: 3
        waitDuration: 200ms
        retryExceptions:
          - java.net.SocketTimeoutException
          - org.springframework.web.client.HttpServerErrorException
        ignoreExceptions:
          - java.lang.IllegalArgumentException


# here limit referesh period is 4s and limit for period is 2 it means 2 requests are allowed in 4s
#
  ratelimiter:
    instances:
      getAllUsersRateLimiter :
        timeoutDuration: 0s   # this means fail immediately if we keep timeoutDuration as 1s the thread will wait for 1s and it will be blocked during that time 
        limitRefreshPeriod: 4s
        limitForPeriod: 2



